---
- name: Aplicar credenciales via CaC con Ansible Vault
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - secrets.yml
    - credentials.yml

  tasks:
    - name: Crear/actualizar credenciales en AAP
      ansible.controller.credential:
        controller_host: "{{ controller_hostname }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: "{{ controller_validate_certs }}"
        name: "{{ item.name }}"
        organization: "{{ item.organization }}"
        credential_type: "{{ item.credential_type }}"
        description: "{{ item.description | default(omit) }}"
        inputs: "{{ item.inputs }}"
        state: present
      loop: "{{ controller_credentials }}"
      loop_control:
        label: "{{ item.name }}"
      no_log: true
