---
- name: "CaC - Configuración común (organizaciones y equipos)"
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../common/secrets.yml
    - ../common/organizations.yml

  vars:
    controller_hostname: "{{ vault_controller_hostname }}"
    controller_username: "{{ vault_controller_username }}"
    controller_password: "{{ vault_controller_password }}"
    controller_validate_certs: false

  roles:
    - role: infra.controller_configuration.dispatch
