---
- name: "CaC - Aplicar configuración de {{ torre }}"
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../common/secrets.yml
    - "../{{ torre }}/secrets.yml"
    - "../{{ torre }}/credentials.yml"
    - "../{{ torre }}/projects.yml"
    - "../{{ torre }}/inventories.yml"
    - "../{{ torre }}/job_templates.yml"

  vars:
    controller_hostname: "{{ vault_controller_hostname }}"
    controller_username: "{{ vault_controller_username }}"
    controller_password: "{{ vault_controller_password }}"
    controller_validate_certs: false

  roles:
    - role: infra.controller_configuration.dispatch
