---
name: Aplicar credenciales a AAP

on:
  push:
    branches: [main]
    paths:
      - 'credentials.yml'
  workflow_dispatch:

jobs:
  apply:
    runs-on: self-hosted    # necesario si AAP no es accesible desde internet
    steps:
      - uses: actions/checkout@v4

      - name: Instalar ansible.controller
        run: ansible-galaxy collection install ansible.controller

      - name: Aplicar credenciales
        run: |
          ansible-playbook aplicar_credenciales_ghsecrets.yml \
            -e "controller_password=${{ secrets.CONTROLLER_PASSWORD }}" \
            -e "vault_machine_password=${{ secrets.MACHINE_PASSWORD }}" \
            -e "vault_vcenter_password=${{ secrets.VCENTER_PASSWORD }}" \
            -e "vault_aap_token=${{ secrets.AAP_TOKEN }}"
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
